server:
  port: 8083
  servlet:
    context-path: /dsl-idp

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: DEBUG

spring:
  thymeleaf:
    cache: false

