server:
  port: 8001

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml2: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    saml2:
      identity-provider:
        entity-id: ~
        sign-metadata: true
        sign-assertions: true
        want-requests-signed: true
        keys:
          active:
            - id: key1
              private: |
                private pem key here
              passphrase: password
              certificate: |
                x509 certificate here
          standby:
            - id: key2
              private: |
                private pem key here
              passphrase: password
              certificate: |
                x509 certificate here
            - id: key3
              private: |
                private pem key here
              passphrase: password
              certificate: |
                x509 certificate here
        providers:
        - name: spring-security-saml-sp
          metadata: |
            <md:EntityDescriptor ID="64e702d9-b8f1-4cd4-ab8d-a8c6ab5d74e4" entityID="http://localhost:8000"
                                 xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata">
              <md:SPSSODescriptor AuthnRequestsSigned="false" ID="6af07992-f76b-478d-804a-bfcb0e0c0c97" WantAssertionsSigned="true"
                                  protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
                <md:Extensions/>
                <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                                        Location="http://localhost:8000/saml/sp/logout"/>
                <md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>
                <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
                <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                                             Location="http://localhost:8000/saml/sp/SSO" index="0" isDefault="true"/>
                <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                                             Location="http://localhost:8000/saml/sp/SSO" index="1" isDefault="false"/>
                <md:AttributeConsumingService index="0" isDefault="true"/>
              </md:SPSSODescriptor>
            </md:EntityDescriptor>
          linktext: Spring Security SAML SP

